sudo: required
service:
       - docker

  befor_install:
          - docker build -t 6122420458/docker-react -f Dockerfile.dev .

 script:
         - docker run -e CI=true 6122420458/docker-react npm run test


